from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Float, JSON
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from geoalchemy2 import Geometry
from app.db.session import Base

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    phone = Column(String, unique=True, nullable=False, index=True)
    language_preference = Column(String, default="en")
    hashed_password = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    devices = relationship("Device", back_populates="user")
    farms = relationship("Farm", back_populates="owner")

class Device(Base):
    __tablename__ = "devices"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    device_uid = Column(String, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    user = relationship("User", back_populates="devices")

class Farm(Base):
    __tablename__ = "farms"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    name = Column(String, nullable=True)
    # store polygon in WKT/EPSG:4326
    geom = Column(Geometry("POLYGON", srid=4326), nullable=True)
    area_ha = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    owner = relationship("User", back_populates="farms")
    soils = relationship("SoilSample", back_populates="farm")
    predictions = relationship("Prediction", back_populates="farm")

class SoilSample(Base):
    __tablename__ = "soil_samples"
    id = Column(Integer, primary_key=True, index=True)
    farm_id = Column(Integer, ForeignKey("farms.id"))
    sample_date = Column(DateTime(timezone=True), server_default=func.now())
    ph = Column(Float)
    n = Column(Float)  # nitrogen
    p = Column(Float)
    k = Column(Float)
    extra = Column(JSON, nullable=True)

    farm = relationship("Farm", back_populates="soils")

class Prediction(Base):
    __tablename__ = "predictions"
    id = Column(Integer, primary_key=True, index=True)
    farm_id = Column(Integer, ForeignKey("farms.id"))
    crop = Column(String, nullable=False)
    date_run = Column(DateTime(timezone=True), server_default=func.now())
    predicted_yield_kg_per_ha = Column(Float)
    model_version = Column(String, default="baseline-v0")
    inputs = Column(JSON, nullable=True)

    farm = relationship("Farm", back_populates="predictions")

# Add these toward the end of models.py (after Prediction)
from sqlalchemy import UniqueConstraint

class SyncLog(Base):
    __tablename__ = "sync_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    client_id = Column(String, index=True)   # UUID generated by client to dedupe
    record_type = Column(String)             # e.g., "soil_sample", "farm"
    server_id = Column(Integer, nullable=True) # created server-side record id
    payload = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    __table_args__ = (UniqueConstraint("user_id", "client_id", "record_type", name="uq_sync_client"),)

class RefreshToken(Base):
    __tablename__ = "refresh_tokens"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    device_id = Column(Integer, ForeignKey("devices.id"), nullable=True)
    token = Column(String, nullable=False, unique=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class WeatherData(Base):
    __tablename__ = "weather_data"
    id = Column(Integer, primary_key=True, index=True)
    farm_id = Column(Integer, ForeignKey("farms.id"), nullable=True, index=True)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    temperature = Column(Float, nullable=True)  # in Celsius
    humidity = Column(Float, nullable=True)  # percentage
    pressure = Column(Float, nullable=True)  # in hPa
    wind_speed = Column(Float, nullable=True)  # in m/s
    wind_direction = Column(Float, nullable=True)  # in degrees
    precipitation = Column(Float, nullable=True)  # in mm
    uv_index = Column(Float, nullable=True)
    visibility = Column(Float, nullable=True)  # in meters
    weather_description = Column(String, nullable=True)  # e.g., "Clear sky", "Rain"
    weather_icon = Column(String, nullable=True)  # icon code from API
    forecast_data = Column(JSON, nullable=True)  # store forecast data
    agromonitoring_data = Column(JSON, nullable=True)  # store agromonitoring data
    recorded_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    
    farm = relationship("Farm", backref="weather_records")

